- name: 'Install dependencies.'
  become: yes
  package:
    name: '{{ item }}'
    state: 'present'
  with_items: '{{ kong_dependencies }}'

- name: 'Install Kong.'
  become: yes
  yum:
    name: '{{ kong_url }}'
    state: 'present'
  register: 'kong_installed'
