---
# tasks file for k8s
- name: update all packages
  command: yum -y update
 
  
- name: install network tools
  yum:
    name: net-tools

- name: install ntp
  yum:
    name: ntp
 
- name: check ntpd service is running
  command: systemctl status ntpd
  register: result
  ignore_errors: True
 
    
- name: configure and sync ntp
  command: "{{item}}"
  with_items:
    - chkconfig ntpd on
    - ntpdate pool.ntp.org
  when: result is failed
   

- name: start service ntp, if not running
  service:
    name: ntpd
    state: started
 
- name: turn off firewall for install
  command: systemctl disable firewalld
  
- name: disable SELinux
  command: setenforce 0

- name: disable SELinux on reboot
  selinux:
    state: disabled

- name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present