# roles/bind/defaults/main.yml
---

bind_zone_master_server_ip: 192.168.2.171

bind_log: "data/named.run"
 
bind_zone_domains:
  - name: 'internal.navitas-labs.com'
    networks:
      - '192.168.2'
    ipv6_networks:
      - '2001:db9::/48'
    name_servers:
      - ns1.internal.navitas-labs.com.
    hostmaster_email: admin
    hosts:
      - name: jenkins.internal.navitas-labs.com
        ip: 192.168.2.172
        ipv6: '2001:db9::1'
        aliases:
          - jenkins

# List of acls.
bind_acls: []

# List of IPv4 address of the network interface(s) to listen on. Set to "any"
# to listen on all interfaces
bind_listen_ipv4:
  - "127.0.0.1"

# List of IPv6 address of the network interface(s) to listen on.
bind_listen_ipv6:
  - "::1"

# List of hosts that are allowed to query this DNS server.
bind_allow_query:
  - "localhost"

# Determines whether recursion should be allowed. Typically, an authoritative
# name server should have recursion turned OFF.
bind_recursion: false
bind_allow_recursion:
  - "any"

# Allows BIND to be set up as a caching name server
bind_forward_only: false

# List of name servers to forward DNS requests to.
bind_forwarders:
   - '8.8.8.8'
   - '8.8.4.4'
# DNS round robin order (random or cyclic)
bind_rrset_order: "random"

# DNSSEC configuration
bind_dnssec_enable: true
bind_dnssec_validation: true

bind_extra_include_files: []

# SOA information
bind_zone_ttl: "1W"
bind_zone_time_to_refresh: "1D"
bind_zone_time_to_retry: "1H"
bind_zone_time_to_expire: "1W"
bind_zone_minimum_ttl: "1D"

# Custom location for master zone files
bind_zone_dir: "{{ bind_dir }}"
# File mode for master zone files (needs to be something like 0660 for dynamic updates)
bind_zone_file_mode: "0640"
