---
# handlers file for postgres
- name: restart postgresql
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
    enabled: yes

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
   