---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644

- name: Ensure nginx is installed.
  package:
    name: "{{ nginx_package_name }}"
    state: present
    
- name: Create Nginx ssl  directory
  file:
    state=directory
    mode=0600
    dest="{{nginx_ssl_location}}"

- name: Start nginx
  service: name=nginx state=started enabled=true
